version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: copallet-postgres
    environment:
      POSTGRES_DB: copallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - copallet-network

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: copallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - copallet-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: copallet-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: copallet
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      PORT: 3001
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - copallet-network
    command: npm run dev

  # Frontend (optional - for full stack development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: copallet-frontend
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - copallet-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  copallet-network:
    driver: bridge
